# **Breast Cancer Detection**

In [136]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

In [137]:
data = load_breast_cancer()

In [138]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [139]:
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [140]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [141]:
print(data['data'])

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [142]:
data['data'].shape


(569, 30)

In [143]:
data['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [144]:
j=0
print("Tumor 1\n")
for i in data['feature_names']:
  print(i,":",data['data'][0][j])
  j+=1

Tumor 1

mean radius : 17.99
mean texture : 10.38
mean perimeter : 122.8
mean area : 1001.0
mean smoothness : 0.1184
mean compactness : 0.2776
mean concavity : 0.3001
mean concave points : 0.1471
mean symmetry : 0.2419
mean fractal dimension : 0.07871
radius error : 1.095
texture error : 0.9053
perimeter error : 8.589
area error : 153.4
smoothness error : 0.006399
compactness error : 0.04904
concavity error : 0.05373
concave points error : 0.01587
symmetry error : 0.03003
fractal dimension error : 0.006193
worst radius : 25.38
worst texture : 17.33
worst perimeter : 184.6
worst area : 2019.0
worst smoothness : 0.1622
worst compactness : 0.6656
worst concavity : 0.7119
worst concave points : 0.2654
worst symmetry : 0.4601
worst fractal dimension : 0.1189


## Printing the Value of Each Feature for Every Tumor



In [145]:
for k in range(len(data['data'])):
  j=0
  print("Tumor number ",k+1,"\n")
  for i in data['feature_names']:
    print(i,":",data['data'][k][j])
    j+=1
  k+=1
  print("\n")

Streaming output truncated to the last 5000 lines.


Tumor number  423 

mean radius : 11.61
mean texture : 16.02
mean perimeter : 75.46
mean area : 408.2
mean smoothness : 0.1088
mean compactness : 0.1168
mean concavity : 0.07097
mean concave points : 0.04497
mean symmetry : 0.1886
mean fractal dimension : 0.0632
radius error : 0.2456
texture error : 0.7339
perimeter error : 1.667
area error : 15.89
smoothness error : 0.005884
compactness error : 0.02005
concavity error : 0.02631
concave points error : 0.01304
symmetry error : 0.01848
fractal dimension error : 0.001982
worst radius : 12.64
worst texture : 19.67
worst perimeter : 81.93
worst area : 475.7
worst smoothness : 0.1415
worst compactness : 0.217
worst concavity : 0.2302
worst concave points : 0.1105
worst symmetry : 0.2787
worst fractal dimension : 0.07427


Tumor number  424 

mean radius : 13.66
mean texture : 19.13
mean perimeter : 89.46
mean area : 575.3
mean smoothness : 0.09057
mean compactness : 0.1147
mean concavity :

In [146]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [147]:
data['target_names']

array(['malignant', 'benign'], dtype='<U9')

In [148]:
data['filename']

'/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/breast_cancer.csv'

In [149]:
feature = data['data']

In [150]:
label = data['target']

In [151]:
feature.shape

(569, 30)

In [152]:
label.shape

(569,)

## Standardisation of All Values

In [153]:
scale = StandardScaler()
feature = scale.fit_transform(feature)

## Observing the Difference in the Features after Standardisation

In [154]:
j=0
print("Tumor 1\n")
for i in data['feature_names']:
  print(i,":",feature[0][j])
  j+=1

Tumor 1

mean radius : 1.0970639814699807
mean texture : -2.0733350146975935
mean perimeter : 1.2699336881399383
mean area : 0.9843749048031144
mean smoothness : 1.568466329243428
mean compactness : 3.2835146709868264
mean concavity : 2.652873983743168
mean concave points : 2.532475216403245
mean symmetry : 2.2175150059646405
mean fractal dimension : 2.255746885296269
radius error : 2.4897339267376193
texture error : -0.5652650590684639
perimeter error : 2.833030865855184
area error : 2.4875775569611043
smoothness error : -0.21400164666895383
compactness error : 1.3168615683959484
concavity error : 0.72402615808036
concave points error : 0.6608199414286064
symmetry error : 1.1487566671861758
fractal dimension error : 0.9070830809973359
worst radius : 1.8866896251792757
worst texture : -1.3592934737640827
worst perimeter : 2.3036006236225606
worst area : 2.0012374893299207
worst smoothness : 1.3076862710715387
worst compactness : 2.616665023512603
worst concavity : 2.1095263465722556
wo

In [155]:
print(feature[0])
print(data['target_names'][label[0]])

[ 1.09706398 -2.07333501  1.26993369  0.9843749   1.56846633  3.28351467
  2.65287398  2.53247522  2.21751501  2.25574689  2.48973393 -0.56526506
  2.83303087  2.48757756 -0.21400165  1.31686157  0.72402616  0.66081994
  1.14875667  0.90708308  1.88668963 -1.35929347  2.30360062  2.00123749
  1.30768627  2.61666502  2.10952635  2.29607613  2.75062224  1.93701461]
malignant


## Converting the data into a Tabular Dataset


In [156]:
df = pd.DataFrame(feature,columns= data['feature_names'])

In [157]:
df.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0     1.097064     -2.073335  ...        2.750622                 1.937015
1     1.829821     -0.353632  ...       -0.243890                 0.281190
2     1.579888      0.456187  ...        1.152255                 0.201391
3    -0.768909      0.253732  ...        6.046041                 4.935010
4     1.750297     -1.151816  ...       -0.868353                -0.397100

[5 rows x 30 columns]

## Splitting the Dataset into Training , Testing and Validation

In [158]:
X_train = feature[:500]
Y_train = label[:500]
X_val = feature[500:535]
Y_val = label[500:535]
X_test = feature[535:]
Y_test = label[535:]

## Checking if the Splitting is done is correct proportion

In [159]:
print(X_train.shape)
print(Y_train.shape)
print(X_val.shape)
print(Y_val.shape)
print(X_test.shape)
print(Y_test.shape)

(500, 30)
(500,)
(35, 30)
(35,)
(34, 30)
(34,)


## **Deep Learning Model Implementation**

### Creating an Empty Neural Network 

In [160]:
model = Sequential()

### Adding the Layers of the Neural Network & Compiling the Model

In [161]:
model.add(Dense(15 , activation= 'relu', input_dim = 30))
model.add(Dense(8 , activation= 'relu'))
model.add(Dense(1 , activation= 'sigmoid'))
model.compile(loss ='binary_crossentropy' , optimizer= 'adam' , metrics= ['accuracy'])

### Training the Model

In [162]:
model.fit(X_train , Y_train , epochs= 10, validation_data = (X_val , Y_val)) 

Epoch 1/10
16/16 [==============================] - 10s 123ms/step - loss: 0.6407 - accuracy: 0.6340 - val_loss: 0.6441 - val_accuracy: 0.7429
Epoch 2/10
16/16 [==============================] - 0s 3ms/step - loss: 0.5668 - accuracy: 0.7600 - val_loss: 0.5837 - val_accuracy: 0.8286
Epoch 3/10
16/16 [==============================] - 0s 4ms/step - loss: 0.4909 - accuracy: 0.8920 - val_loss: 0.5134 - val_accuracy: 0.9429
Epoch 4/10
16/16 [==============================] - 0s 3ms/step - loss: 0.4074 - accuracy: 0.9320 - val_loss: 0.4356 - val_accuracy: 0.9143
Epoch 5/10
16/16 [==============================] - 0s 4ms/step - loss: 0.3295 - accuracy: 0.9380 - val_loss: 0.3617 - val_accuracy: 0.9143
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 0.2683 - accuracy: 0.9400 - val_loss: 0.3074 - val_accuracy: 0.9143
Epoch 7/10
16/16 [==============================] - 0s 3ms/step - loss: 0.2227 - accuracy: 0.9480 - val_loss: 0.2644 - val_accuracy: 0.9429
Epoch 8/10
16/16 

In [163]:
model.evaluate(X_test,Y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.1447 - accuracy: 0.9706


[0.14473794400691986, 0.970588207244873]

### Passing One Tumor at a Time through the Neural Network

In [164]:
model.fit(X_train , Y_train , batch_size = 1 , epochs=10 , validation_data = (X_val , Y_val)) 

Epoch 1/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0838 - accuracy: 0.9820 - val_loss: 0.0529 - val_accuracy: 1.0000
Epoch 2/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0581 - accuracy: 0.9800 - val_loss: 0.0480 - val_accuracy: 1.0000
Epoch 3/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0485 - accuracy: 0.9880 - val_loss: 0.0506 - val_accuracy: 0.9714
Epoch 4/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0412 - accuracy: 0.9860 - val_loss: 0.0358 - val_accuracy: 1.0000
Epoch 5/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0392 - accuracy: 0.9900 - val_loss: 0.0400 - val_accuracy: 1.0000
Epoch 6/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0335 - accuracy: 0.9920 - val_loss: 0.0489 - val_accuracy: 0.9714
Epoch 7/10
500/500 [==============================] - 1s 2ms/step - loss: 0.0291 - accuracy: 0.9920 - val_loss: 0.0467 - val_accuracy: 0.9714
Epoch 

In [165]:
model.evaluate(X_test,Y_test)

2/2 [==============================] - 0s 7ms/step - loss: 0.0858 - accuracy: 0.9706


[0.08579153567552567, 0.970588207244873]

### Predicting the Nature of Tumor Using the Model

In [166]:
for i in range(len(X_test)):
  sample = X_test[i]
  sample = np.reshape(sample,(1,30))
  if (model.predict(sample) > 0.5):
    print("By Model Prediction the Tumor is - Benign")
  else:
    print("By Model Prediction the Tumor is - Malignant")
  if (Y_test[i]==0):
    print("Actual Nature of Tumor is - Malignant")
  else:
      print("Actual Nature of Tumor is - Benign")
  print("-------------\n")

By Model Prediction the Tumor is - Malignant
Actual Nature of Tumor is - Malignant
-------------

By Model Prediction the Tumor is - Malignant
Actual Nature of Tumor is - Malignant
-------------

By Model Prediction the Tumor is - Benign
Actual Nature of Tumor is - Benign
-------------

By Model Prediction the Tumor is - Benign
Actual Nature of Tumor is - Benign
-------------

By Model Prediction the Tumor is - Benign
Actual Nature of Tumor is - Benign
-------------

By Model Prediction the Tumor is - Benign
Actual Nature of Tumor is - Benign
-------------

By Model Prediction the Tumor is - Malignant
Actual Nature of Tumor is - Benign
-------------

By Model Prediction the Tumor is - Benign
Actual Nature of Tumor is - Benign
-------------

By Model Prediction the Tumor is - Benign
Actual Nature of Tumor is - Benign
-------------

By Model Prediction the Tumor is - Benign
Actual Nature of Tumor is - Benign
-------------

By Model Prediction the Tumor is - Benign
Actual Nature of Tumor 